stages:
  load_data:
    cmd: python source/load_data.py --config=params.yaml
    deps:
      - source/get_data.py
      - source/load_data.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv
