stages:
  load_data:
    cmd: python source/load_data.py --config=params.yaml
    deps:
      - source/get_data.py
      - source/load_data.py
      - data_given/winequality.csv
    outs:
      - data/raw/winequality.csv
    
  split_data:
    cmd: python source/split_data.py --config=params.yaml
    deps:
      - source/get_data.py
      - source/split_data.py
      - data/raw/winequality.csv
    outs:
      - data/processed/train_winequality.csv
      - data/processed/test_winequality.csv

